name: Push Charts
description: Package Helm charts and push them as OCI artifacts to a registry. Emits a JSON array of charts that include ArtifactHub metadata.
inputs:
  charts_dir:
    description: Directory containing charts
    required: false
    default: "charts"
  registry:
    description: OCI registry (e.g. ghcr.io/org/helm)
    required: false
    default: "ghcr.io/${{ github.repository_owner }}/helm"
outputs:
  artifacthub_charts:
    description: JSON array of {name,version,path} for charts that contain artifacthub-repo.yml
    value: ${{ steps.package_and_push.outputs.artifacthub_charts }}
runs:
  using: "composite"
  steps:
    - id: package_and_push
      name: Package and push charts
      shell: bash
      env:
        CHARTS_DIR: "${{ inputs.charts_dir }}"
        REGISTRY: "${{ inputs.registry }}"
      run: |
        set -eo pipefail
        mkdir -p /tmp/oci-packages
        rm -f /tmp/oci-packages/* || true
        jq -n '[]' > /tmp/artifacthub_list.json

        for chart_dir in "$CHARTS_DIR"/*; do
          if [ ! -d "$chart_dir" ]; then
            continue
          fi

          echo "Packaging chart: $chart_dir"

          # Ensure chart dependencies are present (download or build them)
          echo "Updating chart dependencies for $chart_dir"
          if ! (cd "$chart_dir" && helm dependency update); then
            echo "helm dependency update failed for $chart_dir; attempting helm dependency build as fallback"
            if ! (cd "$chart_dir" && helm dependency build); then
              echo "ERROR: failed to fetch/build dependencies for $chart_dir" >&2
              echo "Chart.yaml contents:" && sed -n '1,200p' "$chart_dir/Chart.yaml" || true
              echo "If this chart has external dependencies, run 'helm repo add' for the required repos or commit the dependency charts into the chart's 'charts/' directory." >&2
              exit 1
            fi
          fi

          helm package "$chart_dir" --destination /tmp/oci-packages

          for pkg in /tmp/oci-packages/*.tgz; do
            [ -e "$pkg" ] || continue

            echo "Pushing package: $pkg"
            helm push "$pkg" oci://"${REGISTRY%/}"

            name=$(tar -xOf "$pkg" --wildcards '*/Chart.yaml' | awk '/^name:/ {print $2; exit}')
            version=$(tar -xOf "$pkg" --wildcards '*/Chart.yaml' | awk '/^version:/ {print $2; exit}')

            if [ -z "$name" ] || [ -z "$version" ]; then
              echo "Failed to extract name/version from $pkg" >&2
              exit 1
            fi

            if [ -f "$chart_dir/artifacthub-repo.yml" ]; then
              jq --arg n "$name" --arg v "$version" --arg p "$chart_dir" '. += [{name:$n, version:$v, path:$p}]' /tmp/artifacthub_list.json > /tmp/artifacthub_list.json.tmp && mv /tmp/artifacthub_list.json.tmp /tmp/artifacthub_list.json
            fi
          done
        done

        # Output compact JSON array
        ARTIFACTHUB_JSON=$(jq -c '.' /tmp/artifacthub_list.json)
        echo "artifacthub_charts=$ARTIFACTHUB_JSON" >> "$GITHUB_OUTPUT"

    - name: Show pushed charts (debug)
      if: always()
      shell: bash
      run: |
        echo "ArtifactHub charts: $(cat /tmp/artifacthub_list.json || echo '[]')"
