name: Sign OCI artifact
description: Sign an OCI artifact using cosign (keyless with GitHub OIDC).
inputs:
  image:
    description: Full OCI image reference (e.g. ghcr.io/org/helm/name:version)
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0

    - name: Sign image (keyless)
      shell: bash
      env:
        IMAGE: "${{ inputs.image }}"
      run: |
        set -eo pipefail
        COSIGN_EXPERIMENTAL="true" cosign sign --yes "$IMAGE"
