name: Find Charts to Release
description: Compare local chart versions with remote (OCI) versions and list charts to release.
inputs:
  charts_json:
    description: JSON array of charts (from `list-charts`). **Required** — the action will not scan local directories.
    required: true
  registry:
    description: OCI registry root (e.g. ghcr.io/org/helm)
    required: false
    default: "ghcr.io/${{ github.repository_owner }}/helm"
outputs:
  to_release:
    description: JSON array of charts that need to be released (local version > remote version)
    value: ${{ steps.find.outputs.to_release }}
  release_needed:
    description: "true if `to_release` array is not empty ('true' or 'false')"
    value: ${{ steps.find.outputs.release_needed }}
runs:
  using: composite
  steps:
    - name: Find remote versions and compare
      id: find
      shell: bash
      run: |
        set -eo pipefail
        CHARTS_JSON_INPUT='${{ inputs.charts_json }}'
        REGISTRY='${{ inputs.registry }}'

        jq -n '[]' > /tmp/all.json
        jq -n '[]' > /tmp/to_release.json

        if [ -n "$CHARTS_JSON_INPUT" ]; then
          charts=$(echo "$CHARTS_JSON_INPUT")
        else
          echo "No charts_json provided to find-charts-to-release; please run list-charts and pass its output." >&2
          exit 1
        fi

        for row in $(echo "$charts" | jq -c '.[]'); do
          name=$(echo "$row" | jq -r '.name')
          path=$(echo "$row" | jq -r '.path')
          local_version=$(echo "$row" | jq -r '.version')

          remote_version=null
          set +e
          out=$(helm show chart oci://"${REGISTRY%/}"/"${name}" 2>&1)
          rc=$?
          set -e
          if [ $rc -ne 0 ]; then
            echo "helm show chart failed for $name: $out" >&2
            if echo "$out" | grep -qi "manifest" || echo "$out" | grep -qi "not found"; then
              remote_version=null
            else
              echo "Error retrieving remote chart for $name" >&2
              exit 1
            fi
          else
            remote_version=$(echo "$out" | awk '/^version:/ {print $2; exit}' || true)
          fi

          # compare versions: if remote_version is null => schedule release
          should_release=false
          if [ "$remote_version" = "null" ] || [ -z "$remote_version" ]; then
            should_release=true
          else
            # pick higher version using sort -V
            if [ "$local_version" != "$remote_version" ]; then
              high=$(printf '%s\n%s\n' "$remote_version" "$local_version" | sort -V | tail -n1)
              if [ "$high" = "$local_version" ]; then
                should_release=true
              fi
            fi
          fi

          jq --arg n "$name" --arg p "$path" --arg lv "$local_version" --arg rv "$remote_version" '. += [{name:$n,path:$p,local_version:$lv,remote_version:$rv}]' /tmp/all.json > /tmp/all.json.tmp && mv /tmp/all.json.tmp /tmp/all.json

          if [ "$should_release" = true ]; then
            jq --arg n "$name" --arg p "$path" --arg lv "$local_version" --arg rv "$remote_version" '. += [{name:$n,path:$p,local_version:$lv,remote_version:$rv}]' /tmp/to_release.json > /tmp/to_release.json.tmp && mv /tmp/to_release.json.tmp /tmp/to_release.json
          fi
        done

        ALL=$(jq -c '.' /tmp/all.json)
        TODO=$(jq -c '.' /tmp/to_release.json)
        echo "to_release=$TODO" >> "$GITHUB_OUTPUT"
        # set release_needed output to 'true' if to_release contains any items, else 'false'
        if [ -s /tmp/to_release.json ] && [ "$(jq -r 'length' /tmp/to_release.json)" -gt 0 ]; then
          echo "release_needed=true" >> "$GITHUB_OUTPUT"
        else
          echo "release_needed=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Show charts to release
      shell: bash
      run: |
        echo "All charts:"
        if [ -s /tmp/all.json ]; then
          cat /tmp/all.json | jq '.'
        else
          echo '[]'
        fi
        echo "Charts to release:"
        if [ -s /tmp/to_release.json ]; then
          cat /tmp/to_release.json | jq '.'
        else
          echo '[]'
        fi
