name: Release Charts
description: Prepare and release charts listed in `to_release` JSON package, sign, push OCI, sign with cosign, publish ArtifactHub metadata.
inputs:
  to_release_json:
    description: JSON array as produced by `find-charts-to-release` (to_release)
    required: true
  registry:
    description: OCI registry (e.g. ghcr.io/org/helm)
    required: false
    default: "ghcr.io/${{ github.repository_owner }}/helm"
runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0

    - name: Install ORAS
      shell: bash
      run: |
        curl -LO https://github.com/oras-project/oras/releases/download/v1.3.0/oras_1.3.0_linux_amd64.tar.gz
        tar -xzf oras_1.3.0_linux_amd64.tar.gz
        sudo mv oras /usr/local/bin/oras

    - name: Install Helm Sigstore Plugin
      shell: bash
      run: |
        set -eo pipefail
        helm plugin install https://github.com/sigstore/helm-sigstore --verify=false || true

    - name: Release charts
      shell: bash
      env:
        TO_RELEASE: '${{ inputs.to_release_json }}'
        REGISTRY: '${{ inputs.registry }}'
      run: |
        set -eo pipefail
        jq -n '[]' > /tmp/release_report.json

        for row in $(echo "$TO_RELEASE" | jq -c '.[]'); do
          name=$(echo "$row" | jq -r '.name')
          path=$(echo "$row" | jq -r '.path')
          version=$(echo "$row" | jq -r '.local_version')

          echo "Preparing $name version $version from $path"
          if ! (cd "$path" && helm dependency update >/dev/null 2>&1 || helm dependency build >/dev/null 2>&1); then
            echo "Dependencies update/build failed for $name" >&2
          fi

          pkg_dir=/tmp/release-packages
          mkdir -p "$pkg_dir"
          helm package "$path" --destination "$pkg_dir"

          pkg=$(ls "$pkg_dir"/*.tgz | head -n1)
          if [ -z "$pkg" ]; then
            echo "Packaging failed for $name" >&2
            jq --arg n "$name" --arg v "$version" '. += [{name:$n,version:$v,pushed:false,errors:["packaging_failed"]}]' /tmp/release_report.json > /tmp/release_report.json.tmp && mv /tmp/release_report.json.tmp /tmp/release_report.json
            continue
          fi

          # Sign packaged chart with helm-sigstore (keyless/signing mechanism from plugin)
          echo "Running helm sigstore sign for $pkg"
          helm sigstore sign "$pkg" || echo "helm sigstore sign failed for $pkg" >&2

          # Upload provenance entry to Rekor (optional: helm sigstore upload)
          echo "Attempting to upload provenance to Rekor for $pkg"
          helm sigstore upload "$pkg" || echo "helm sigstore upload failed for $pkg (continuing)" >&2

          image_ref="${REGISTRY%/}/$name:$version"

          # Push chart to OCI registry
          echo "Pushing $pkg to $image_ref"
          helm push "$pkg" oci://"${REGISTRY%/}" || { echo "helm push failed for $pkg" >&2; }

          # Sign pushed OCI artifact with cosign (keyless via OIDC)
          echo "Signing OCI artifact with cosign: $image_ref"
          COSIGN_EXPERIMENTAL="true" cosign sign --yes "$image_ref" || echo "cosign sign failed for $image_ref" >&2

          # publish artifacthub metadata if present
          if [ -f "$path/artifacthub-repo.yml" ]; then
            echo "Publishing ArtifactHub metadata for $name"
            oras push "${image_ref}:artifacthub.io" \
              --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
              "$path/artifacthub-repo.yml":application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml || echo "ArtifactHub publish failed for $name" >&2
          fi

          jq --arg n "$name" --arg v "$version" '. += [{name:$n,version:$v,pushed:true,errors:[]} ]' /tmp/release_report.json > /tmp/release_report.json.tmp && mv /tmp/release_report.json.tmp /tmp/release_report.json
        done

        REPORT=$(jq -c '.' /tmp/release_report.json)
        echo "report=$REPORT" >> "$GITHUB_OUTPUT"
